# Generated by Django 5.2.7 on 2025-10-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notes'},
        ),
    ]
